// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

/**
 * <pre>
 * Describes an enum type.
 * </pre>
 *
 * Protobuf type {@code opensergo.proto.service_contract.v1.EnumDescriptorProto}
 */
public final class EnumDescriptorProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.proto.service_contract.v1.EnumDescriptorProto)
    EnumDescriptorProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnumDescriptorProto.newBuilder() to construct.
  private EnumDescriptorProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnumDescriptorProto() {
    name_ = "";
    value_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnumDescriptorProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnumDescriptorProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              value_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            value_.add(
                input.readMessage(io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            io.opensergo.proto.service_contract.v1.MessageOptions.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = options_.toBuilder();
            }
            options_ = input.readMessage(io.opensergo.proto.service_contract.v1.MessageOptions.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(options_);
              options_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        value_ = java.util.Collections.unmodifiableList(value_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_EnumDescriptorProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_EnumDescriptorProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensergo.proto.service_contract.v1.EnumDescriptorProto.class, io.opensergo.proto.service_contract.v1.EnumDescriptorProto.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.util.List<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto> value_;
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto> getValueList() {
    return value_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder> 
      getValueOrBuilderList() {
    return value_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
   */
  @java.lang.Override
  public int getValueCount() {
    return value_.size();
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto getValue(int index) {
    return value_.get(index);
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder getValueOrBuilder(
      int index) {
    return value_.get(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private io.opensergo.proto.service_contract.v1.MessageOptions options_;
  /**
   * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
   * @return Whether the options field is set.
   */
  @java.lang.Override
  public boolean hasOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
   * @return The options.
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.MessageOptions getOptions() {
    return options_ == null ? io.opensergo.proto.service_contract.v1.MessageOptions.getDefaultInstance() : options_;
  }
  /**
   * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.MessageOptionsOrBuilder getOptionsOrBuilder() {
    return options_ == null ? io.opensergo.proto.service_contract.v1.MessageOptions.getDefaultInstance() : options_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < value_.size(); i++) {
      output.writeMessage(2, value_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getOptions());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < value_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, value_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOptions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensergo.proto.service_contract.v1.EnumDescriptorProto)) {
      return super.equals(obj);
    }
    io.opensergo.proto.service_contract.v1.EnumDescriptorProto other = (io.opensergo.proto.service_contract.v1.EnumDescriptorProto) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!getValueList()
        .equals(other.getValueList())) return false;
    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions()
          .equals(other.getOptions())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (getValueCount() > 0) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValueList().hashCode();
    }
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensergo.proto.service_contract.v1.EnumDescriptorProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Describes an enum type.
   * </pre>
   *
   * Protobuf type {@code opensergo.proto.service_contract.v1.EnumDescriptorProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.proto.service_contract.v1.EnumDescriptorProto)
      io.opensergo.proto.service_contract.v1.EnumDescriptorProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_EnumDescriptorProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_EnumDescriptorProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensergo.proto.service_contract.v1.EnumDescriptorProto.class, io.opensergo.proto.service_contract.v1.EnumDescriptorProto.Builder.class);
    }

    // Construct using io.opensergo.proto.service_contract.v1.EnumDescriptorProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValueFieldBuilder();
        getOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        valueBuilder_.clear();
      }
      if (optionsBuilder_ == null) {
        options_ = null;
      } else {
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_EnumDescriptorProto_descriptor;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.EnumDescriptorProto getDefaultInstanceForType() {
      return io.opensergo.proto.service_contract.v1.EnumDescriptorProto.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.EnumDescriptorProto build() {
      io.opensergo.proto.service_contract.v1.EnumDescriptorProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.EnumDescriptorProto buildPartial() {
      io.opensergo.proto.service_contract.v1.EnumDescriptorProto result = new io.opensergo.proto.service_contract.v1.EnumDescriptorProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (optionsBuilder_ == null) {
          result.options_ = options_;
        } else {
          result.options_ = optionsBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensergo.proto.service_contract.v1.EnumDescriptorProto) {
        return mergeFrom((io.opensergo.proto.service_contract.v1.EnumDescriptorProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensergo.proto.service_contract.v1.EnumDescriptorProto other) {
      if (other == io.opensergo.proto.service_contract.v1.EnumDescriptorProto.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (valueBuilder_ == null) {
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
      } else {
        if (!other.value_.isEmpty()) {
          if (valueBuilder_.isEmpty()) {
            valueBuilder_.dispose();
            valueBuilder_ = null;
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValueFieldBuilder() : null;
          } else {
            valueBuilder_.addAllMessages(other.value_);
          }
        }
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opensergo.proto.service_contract.v1.EnumDescriptorProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opensergo.proto.service_contract.v1.EnumDescriptorProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto> value_ =
      java.util.Collections.emptyList();
    private void ensureValueIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        value_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto>(value_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder> valueBuilder_;

    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto> getValueList() {
      if (valueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(value_);
      } else {
        return valueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public int getValueCount() {
      if (valueBuilder_ == null) {
        return value_.size();
      } else {
        return valueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto getValue(int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);
      } else {
        return valueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder setValue(
        int index, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
      } else {
        valueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder setValue(
        int index, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.set(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder addValue(io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
      } else {
        valueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder addValue(
        int index, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(index, value);
        onChanged();
      } else {
        valueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder addValue(
        io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder addValue(
        int index, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder addAllValue(
        java.lang.Iterable<? extends io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto> values) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
      } else {
        valueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public Builder removeValue(int index) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.remove(index);
        onChanged();
      } else {
        valueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder getValueBuilder(
        int index) {
      return getValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder getValueOrBuilder(
        int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);  } else {
        return valueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public java.util.List<? extends io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder> 
         getValueOrBuilderList() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(value_);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder addValueBuilder() {
      return getValueFieldBuilder().addBuilder(
          io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder addValueBuilder(
        int index) {
      return getValueFieldBuilder().addBuilder(
          index, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.EnumValueDescriptorProto value = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder> 
         getValueBuilderList() {
      return getValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProto.Builder, io.opensergo.proto.service_contract.v1.EnumValueDescriptorProtoOrBuilder>(
                value_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private io.opensergo.proto.service_contract.v1.MessageOptions options_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.MessageOptions, io.opensergo.proto.service_contract.v1.MessageOptions.Builder, io.opensergo.proto.service_contract.v1.MessageOptionsOrBuilder> optionsBuilder_;
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     * @return The options.
     */
    public io.opensergo.proto.service_contract.v1.MessageOptions getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? io.opensergo.proto.service_contract.v1.MessageOptions.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public Builder setOptions(io.opensergo.proto.service_contract.v1.MessageOptions value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
        onChanged();
      } else {
        optionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public Builder setOptions(
        io.opensergo.proto.service_contract.v1.MessageOptions.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
        onChanged();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public Builder mergeOptions(io.opensergo.proto.service_contract.v1.MessageOptions value) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            options_ != null &&
            options_ != io.opensergo.proto.service_contract.v1.MessageOptions.getDefaultInstance()) {
          options_ =
            io.opensergo.proto.service_contract.v1.MessageOptions.newBuilder(options_).mergeFrom(value).buildPartial();
        } else {
          options_ = value;
        }
        onChanged();
      } else {
        optionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = null;
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.MessageOptions.Builder getOptionsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.MessageOptionsOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ?
            io.opensergo.proto.service_contract.v1.MessageOptions.getDefaultInstance() : options_;
      }
    }
    /**
     * <code>optional .opensergo.proto.service_contract.v1.MessageOptions options = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.MessageOptions, io.opensergo.proto.service_contract.v1.MessageOptions.Builder, io.opensergo.proto.service_contract.v1.MessageOptionsOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.MessageOptions, io.opensergo.proto.service_contract.v1.MessageOptions.Builder, io.opensergo.proto.service_contract.v1.MessageOptionsOrBuilder>(
                getOptions(),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.proto.service_contract.v1.EnumDescriptorProto)
  }

  // @@protoc_insertion_point(class_scope:opensergo.proto.service_contract.v1.EnumDescriptorProto)
  private static final io.opensergo.proto.service_contract.v1.EnumDescriptorProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensergo.proto.service_contract.v1.EnumDescriptorProto();
  }

  public static io.opensergo.proto.service_contract.v1.EnumDescriptorProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnumDescriptorProto>
      PARSER = new com.google.protobuf.AbstractParser<EnumDescriptorProto>() {
    @java.lang.Override
    public EnumDescriptorProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnumDescriptorProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnumDescriptorProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnumDescriptorProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.EnumDescriptorProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

