// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

public interface LocalityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.proto.service_contract.v1.Locality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Region this instance belongs to.
   * </pre>
   *
   * <code>string region = 2;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <pre>
   * Region this instance belongs to.
   * </pre>
   *
   * <code>string region = 2;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * Defines the local service zone where instance is running.
   * </pre>
   *
   * <code>string zone = 3;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <pre>
   * Defines the local service zone where instance is running.
   * </pre>
   *
   * <code>string zone = 3;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();
}
