// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

public interface MethodDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.proto.service_contract.v1.MethodDescriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Input and output type names.  These are resolved in the same way as
   * FieldDescriptor.type_name, but must refer to a message type.
   * </pre>
   *
   * <code>repeated string input_types = 2;</code>
   * @return A list containing the inputTypes.
   */
  java.util.List<java.lang.String>
      getInputTypesList();
  /**
   * <pre>
   * Input and output type names.  These are resolved in the same way as
   * FieldDescriptor.type_name, but must refer to a message type.
   * </pre>
   *
   * <code>repeated string input_types = 2;</code>
   * @return The count of inputTypes.
   */
  int getInputTypesCount();
  /**
   * <pre>
   * Input and output type names.  These are resolved in the same way as
   * FieldDescriptor.type_name, but must refer to a message type.
   * </pre>
   *
   * <code>repeated string input_types = 2;</code>
   * @param index The index of the element to return.
   * @return The inputTypes at the given index.
   */
  java.lang.String getInputTypes(int index);
  /**
   * <pre>
   * Input and output type names.  These are resolved in the same way as
   * FieldDescriptor.type_name, but must refer to a message type.
   * </pre>
   *
   * <code>repeated string input_types = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputTypes at the given index.
   */
  com.google.protobuf.ByteString
      getInputTypesBytes(int index);

  /**
   * <code>repeated string output_types = 3;</code>
   * @return A list containing the outputTypes.
   */
  java.util.List<java.lang.String>
      getOutputTypesList();
  /**
   * <code>repeated string output_types = 3;</code>
   * @return The count of outputTypes.
   */
  int getOutputTypesCount();
  /**
   * <code>repeated string output_types = 3;</code>
   * @param index The index of the element to return.
   * @return The outputTypes at the given index.
   */
  java.lang.String getOutputTypes(int index);
  /**
   * <code>repeated string output_types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputTypes at the given index.
   */
  com.google.protobuf.ByteString
      getOutputTypesBytes(int index);

  /**
   * <pre>
   * Identifies if client streams multiple client messages
   * </pre>
   *
   * <code>optional bool client_streaming = 5;</code>
   * @return Whether the clientStreaming field is set.
   */
  boolean hasClientStreaming();
  /**
   * <pre>
   * Identifies if client streams multiple client messages
   * </pre>
   *
   * <code>optional bool client_streaming = 5;</code>
   * @return The clientStreaming.
   */
  boolean getClientStreaming();

  /**
   * <pre>
   * Identifies if server streams multiple server messages
   * </pre>
   *
   * <code>optional bool server_streaming = 6;</code>
   * @return Whether the serverStreaming field is set.
   */
  boolean hasServerStreaming();
  /**
   * <pre>
   * Identifies if server streams multiple server messages
   * </pre>
   *
   * <code>optional bool server_streaming = 6;</code>
   * @return The serverStreaming.
   */
  boolean getServerStreaming();

  /**
   * <pre>
   * description of this method
   * </pre>
   *
   * <code>optional string description = 7;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <pre>
   * description of this method
   * </pre>
   *
   * <code>optional string description = 7;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * description of this method
   * </pre>
   *
   * <code>optional string description = 7;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string http_paths = 8;</code>
   * @return A list containing the httpPaths.
   */
  java.util.List<java.lang.String>
      getHttpPathsList();
  /**
   * <code>repeated string http_paths = 8;</code>
   * @return The count of httpPaths.
   */
  int getHttpPathsCount();
  /**
   * <code>repeated string http_paths = 8;</code>
   * @param index The index of the element to return.
   * @return The httpPaths at the given index.
   */
  java.lang.String getHttpPaths(int index);
  /**
   * <code>repeated string http_paths = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the httpPaths at the given index.
   */
  com.google.protobuf.ByteString
      getHttpPathsBytes(int index);

  /**
   * <code>repeated string http_methods = 9;</code>
   * @return A list containing the httpMethods.
   */
  java.util.List<java.lang.String>
      getHttpMethodsList();
  /**
   * <code>repeated string http_methods = 9;</code>
   * @return The count of httpMethods.
   */
  int getHttpMethodsCount();
  /**
   * <code>repeated string http_methods = 9;</code>
   * @param index The index of the element to return.
   * @return The httpMethods at the given index.
   */
  java.lang.String getHttpMethods(int index);
  /**
   * <code>repeated string http_methods = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the httpMethods at the given index.
   */
  com.google.protobuf.ByteString
      getHttpMethodsBytes(int index);
}
