// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

/**
 * <pre>
 * Identifier metadata of the Node.
 * </pre>
 *
 * Protobuf type {@code opensergo.proto.service_contract.v1.Node}
 */
public final class Node extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.proto.service_contract.v1.Node)
    NodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Node.newBuilder() to construct.
  private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Node() {
    tag_ = "";
    cluster_ = "";
    env_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Node();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Node(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder subBuilder = null;
            if (identifier_ != null) {
              subBuilder = identifier_.toBuilder();
            }
            identifier_ = input.readMessage(io.opensergo.proto.service_contract.v1.NodeIdentifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(identifier_);
              identifier_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            io.opensergo.proto.service_contract.v1.Locality.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = locality_.toBuilder();
            }
            locality_ = input.readMessage(io.opensergo.proto.service_contract.v1.Locality.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(locality_);
              locality_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            tag_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            cluster_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            env_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_Node_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_Node_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensergo.proto.service_contract.v1.Node.class, io.opensergo.proto.service_contract.v1.Node.Builder.class);
  }

  private int bitField0_;
  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private io.opensergo.proto.service_contract.v1.NodeIdentifier identifier_;
  /**
   * <pre>
   * Identifier that uniquely identifies a process within a VM/container.
   * </pre>
   *
   * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
   * @return Whether the identifier field is set.
   */
  @java.lang.Override
  public boolean hasIdentifier() {
    return identifier_ != null;
  }
  /**
   * <pre>
   * Identifier that uniquely identifies a process within a VM/container.
   * </pre>
   *
   * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
   * @return The identifier.
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.NodeIdentifier getIdentifier() {
    return identifier_ == null ? io.opensergo.proto.service_contract.v1.NodeIdentifier.getDefaultInstance() : identifier_;
  }
  /**
   * <pre>
   * Identifier that uniquely identifies a process within a VM/container.
   * </pre>
   *
   * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.NodeIdentifierOrBuilder getIdentifierOrBuilder() {
    return getIdentifier();
  }

  public static final int LOCALITY_FIELD_NUMBER = 4;
  private io.opensergo.proto.service_contract.v1.Locality locality_;
  /**
   * <pre>
   * Locality specifying where the instance is running.
   * </pre>
   *
   * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
   * @return Whether the locality field is set.
   */
  @java.lang.Override
  public boolean hasLocality() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Locality specifying where the instance is running.
   * </pre>
   *
   * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
   * @return The locality.
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.Locality getLocality() {
    return locality_ == null ? io.opensergo.proto.service_contract.v1.Locality.getDefaultInstance() : locality_;
  }
  /**
   * <pre>
   * Locality specifying where the instance is running.
   * </pre>
   *
   * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.LocalityOrBuilder getLocalityOrBuilder() {
    return locality_ == null ? io.opensergo.proto.service_contract.v1.Locality.getDefaultInstance() : locality_;
  }

  public static final int TAG_FIELD_NUMBER = 5;
  private volatile java.lang.Object tag_;
  /**
   * <code>optional string tag = 5;</code>
   * @return Whether the tag field is set.
   */
  @java.lang.Override
  public boolean hasTag() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string tag = 5;</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tag = 5;</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTER_FIELD_NUMBER = 6;
  private volatile java.lang.Object cluster_;
  /**
   * <code>optional string cluster = 6;</code>
   * @return Whether the cluster field is set.
   */
  @java.lang.Override
  public boolean hasCluster() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string cluster = 6;</code>
   * @return The cluster.
   */
  @java.lang.Override
  public java.lang.String getCluster() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cluster = 6;</code>
   * @return The bytes for cluster.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterBytes() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENV_FIELD_NUMBER = 7;
  private volatile java.lang.Object env_;
  /**
   * <code>optional string env = 7;</code>
   * @return Whether the env field is set.
   */
  @java.lang.Override
  public boolean hasEnv() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string env = 7;</code>
   * @return The env.
   */
  @java.lang.Override
  public java.lang.String getEnv() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      env_ = s;
      return s;
    }
  }
  /**
   * <code>optional string env = 7;</code>
   * @return The bytes for env.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvBytes() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      env_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (identifier_ != null) {
      output.writeMessage(1, getIdentifier());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getLocality());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tag_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cluster_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, env_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (identifier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIdentifier());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLocality());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tag_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cluster_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, env_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensergo.proto.service_contract.v1.Node)) {
      return super.equals(obj);
    }
    io.opensergo.proto.service_contract.v1.Node other = (io.opensergo.proto.service_contract.v1.Node) obj;

    if (hasIdentifier() != other.hasIdentifier()) return false;
    if (hasIdentifier()) {
      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
    }
    if (hasLocality() != other.hasLocality()) return false;
    if (hasLocality()) {
      if (!getLocality()
          .equals(other.getLocality())) return false;
    }
    if (hasTag() != other.hasTag()) return false;
    if (hasTag()) {
      if (!getTag()
          .equals(other.getTag())) return false;
    }
    if (hasCluster() != other.hasCluster()) return false;
    if (hasCluster()) {
      if (!getCluster()
          .equals(other.getCluster())) return false;
    }
    if (hasEnv() != other.hasEnv()) return false;
    if (hasEnv()) {
      if (!getEnv()
          .equals(other.getEnv())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    if (hasLocality()) {
      hash = (37 * hash) + LOCALITY_FIELD_NUMBER;
      hash = (53 * hash) + getLocality().hashCode();
    }
    if (hasTag()) {
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
    }
    if (hasCluster()) {
      hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
      hash = (53 * hash) + getCluster().hashCode();
    }
    if (hasEnv()) {
      hash = (37 * hash) + ENV_FIELD_NUMBER;
      hash = (53 * hash) + getEnv().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.Node parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensergo.proto.service_contract.v1.Node prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Identifier metadata of the Node.
   * </pre>
   *
   * Protobuf type {@code opensergo.proto.service_contract.v1.Node}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.proto.service_contract.v1.Node)
      io.opensergo.proto.service_contract.v1.NodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensergo.proto.service_contract.v1.Node.class, io.opensergo.proto.service_contract.v1.Node.Builder.class);
    }

    // Construct using io.opensergo.proto.service_contract.v1.Node.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLocalityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (identifierBuilder_ == null) {
        identifier_ = null;
      } else {
        identifier_ = null;
        identifierBuilder_ = null;
      }
      if (localityBuilder_ == null) {
        locality_ = null;
      } else {
        localityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      tag_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      cluster_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      env_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_Node_descriptor;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.Node getDefaultInstanceForType() {
      return io.opensergo.proto.service_contract.v1.Node.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.Node build() {
      io.opensergo.proto.service_contract.v1.Node result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.Node buildPartial() {
      io.opensergo.proto.service_contract.v1.Node result = new io.opensergo.proto.service_contract.v1.Node(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (identifierBuilder_ == null) {
        result.identifier_ = identifier_;
      } else {
        result.identifier_ = identifierBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (localityBuilder_ == null) {
          result.locality_ = locality_;
        } else {
          result.locality_ = localityBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.tag_ = tag_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.cluster_ = cluster_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.env_ = env_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensergo.proto.service_contract.v1.Node) {
        return mergeFrom((io.opensergo.proto.service_contract.v1.Node)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensergo.proto.service_contract.v1.Node other) {
      if (other == io.opensergo.proto.service_contract.v1.Node.getDefaultInstance()) return this;
      if (other.hasIdentifier()) {
        mergeIdentifier(other.getIdentifier());
      }
      if (other.hasLocality()) {
        mergeLocality(other.getLocality());
      }
      if (other.hasTag()) {
        bitField0_ |= 0x00000002;
        tag_ = other.tag_;
        onChanged();
      }
      if (other.hasCluster()) {
        bitField0_ |= 0x00000004;
        cluster_ = other.cluster_;
        onChanged();
      }
      if (other.hasEnv()) {
        bitField0_ |= 0x00000008;
        env_ = other.env_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opensergo.proto.service_contract.v1.Node parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opensergo.proto.service_contract.v1.Node) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.opensergo.proto.service_contract.v1.NodeIdentifier identifier_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.NodeIdentifier, io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder, io.opensergo.proto.service_contract.v1.NodeIdentifierOrBuilder> identifierBuilder_;
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     * @return Whether the identifier field is set.
     */
    public boolean hasIdentifier() {
      return identifierBuilder_ != null || identifier_ != null;
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     * @return The identifier.
     */
    public io.opensergo.proto.service_contract.v1.NodeIdentifier getIdentifier() {
      if (identifierBuilder_ == null) {
        return identifier_ == null ? io.opensergo.proto.service_contract.v1.NodeIdentifier.getDefaultInstance() : identifier_;
      } else {
        return identifierBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public Builder setIdentifier(io.opensergo.proto.service_contract.v1.NodeIdentifier value) {
      if (identifierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        identifier_ = value;
        onChanged();
      } else {
        identifierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public Builder setIdentifier(
        io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder builderForValue) {
      if (identifierBuilder_ == null) {
        identifier_ = builderForValue.build();
        onChanged();
      } else {
        identifierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public Builder mergeIdentifier(io.opensergo.proto.service_contract.v1.NodeIdentifier value) {
      if (identifierBuilder_ == null) {
        if (identifier_ != null) {
          identifier_ =
            io.opensergo.proto.service_contract.v1.NodeIdentifier.newBuilder(identifier_).mergeFrom(value).buildPartial();
        } else {
          identifier_ = value;
        }
        onChanged();
      } else {
        identifierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public Builder clearIdentifier() {
      if (identifierBuilder_ == null) {
        identifier_ = null;
        onChanged();
      } else {
        identifier_ = null;
        identifierBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder getIdentifierBuilder() {
      
      onChanged();
      return getIdentifierFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.NodeIdentifierOrBuilder getIdentifierOrBuilder() {
      if (identifierBuilder_ != null) {
        return identifierBuilder_.getMessageOrBuilder();
      } else {
        return identifier_ == null ?
            io.opensergo.proto.service_contract.v1.NodeIdentifier.getDefaultInstance() : identifier_;
      }
    }
    /**
     * <pre>
     * Identifier that uniquely identifies a process within a VM/container.
     * </pre>
     *
     * <code>.opensergo.proto.service_contract.v1.NodeIdentifier identifier = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.NodeIdentifier, io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder, io.opensergo.proto.service_contract.v1.NodeIdentifierOrBuilder> 
        getIdentifierFieldBuilder() {
      if (identifierBuilder_ == null) {
        identifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.NodeIdentifier, io.opensergo.proto.service_contract.v1.NodeIdentifier.Builder, io.opensergo.proto.service_contract.v1.NodeIdentifierOrBuilder>(
                getIdentifier(),
                getParentForChildren(),
                isClean());
        identifier_ = null;
      }
      return identifierBuilder_;
    }

    private io.opensergo.proto.service_contract.v1.Locality locality_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.Locality, io.opensergo.proto.service_contract.v1.Locality.Builder, io.opensergo.proto.service_contract.v1.LocalityOrBuilder> localityBuilder_;
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     * @return Whether the locality field is set.
     */
    public boolean hasLocality() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     * @return The locality.
     */
    public io.opensergo.proto.service_contract.v1.Locality getLocality() {
      if (localityBuilder_ == null) {
        return locality_ == null ? io.opensergo.proto.service_contract.v1.Locality.getDefaultInstance() : locality_;
      } else {
        return localityBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public Builder setLocality(io.opensergo.proto.service_contract.v1.Locality value) {
      if (localityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        locality_ = value;
        onChanged();
      } else {
        localityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public Builder setLocality(
        io.opensergo.proto.service_contract.v1.Locality.Builder builderForValue) {
      if (localityBuilder_ == null) {
        locality_ = builderForValue.build();
        onChanged();
      } else {
        localityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public Builder mergeLocality(io.opensergo.proto.service_contract.v1.Locality value) {
      if (localityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            locality_ != null &&
            locality_ != io.opensergo.proto.service_contract.v1.Locality.getDefaultInstance()) {
          locality_ =
            io.opensergo.proto.service_contract.v1.Locality.newBuilder(locality_).mergeFrom(value).buildPartial();
        } else {
          locality_ = value;
        }
        onChanged();
      } else {
        localityBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public Builder clearLocality() {
      if (localityBuilder_ == null) {
        locality_ = null;
        onChanged();
      } else {
        localityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public io.opensergo.proto.service_contract.v1.Locality.Builder getLocalityBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLocalityFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    public io.opensergo.proto.service_contract.v1.LocalityOrBuilder getLocalityOrBuilder() {
      if (localityBuilder_ != null) {
        return localityBuilder_.getMessageOrBuilder();
      } else {
        return locality_ == null ?
            io.opensergo.proto.service_contract.v1.Locality.getDefaultInstance() : locality_;
      }
    }
    /**
     * <pre>
     * Locality specifying where the instance is running.
     * </pre>
     *
     * <code>optional .opensergo.proto.service_contract.v1.Locality locality = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.Locality, io.opensergo.proto.service_contract.v1.Locality.Builder, io.opensergo.proto.service_contract.v1.LocalityOrBuilder> 
        getLocalityFieldBuilder() {
      if (localityBuilder_ == null) {
        localityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.Locality, io.opensergo.proto.service_contract.v1.Locality.Builder, io.opensergo.proto.service_contract.v1.LocalityOrBuilder>(
                getLocality(),
                getParentForChildren(),
                isClean());
        locality_ = null;
      }
      return localityBuilder_;
    }

    private java.lang.Object tag_ = "";
    /**
     * <code>optional string tag = 5;</code>
     * @return Whether the tag field is set.
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string tag = 5;</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string tag = 5;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tag = 5;</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      tag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tag_ = getDefaultInstance().getTag();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 5;</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      tag_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cluster_ = "";
    /**
     * <code>optional string cluster = 6;</code>
     * @return Whether the cluster field is set.
     */
    public boolean hasCluster() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string cluster = 6;</code>
     * @return The cluster.
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cluster = 6;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cluster = 6;</code>
     * @param value The cluster to set.
     * @return This builder for chaining.
     */
    public Builder setCluster(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cluster = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCluster() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cluster = 6;</code>
     * @param value The bytes for cluster to set.
     * @return This builder for chaining.
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      cluster_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object env_ = "";
    /**
     * <code>optional string env = 7;</code>
     * @return Whether the env field is set.
     */
    public boolean hasEnv() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string env = 7;</code>
     * @return The env.
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string env = 7;</code>
     * @return The bytes for env.
     */
    public com.google.protobuf.ByteString
        getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string env = 7;</code>
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      env_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string env = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      bitField0_ = (bitField0_ & ~0x00000008);
      env_ = getDefaultInstance().getEnv();
      onChanged();
      return this;
    }
    /**
     * <code>optional string env = 7;</code>
     * @param value The bytes for env to set.
     * @return This builder for chaining.
     */
    public Builder setEnvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      env_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.proto.service_contract.v1.Node)
  }

  // @@protoc_insertion_point(class_scope:opensergo.proto.service_contract.v1.Node)
  private static final io.opensergo.proto.service_contract.v1.Node DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensergo.proto.service_contract.v1.Node();
  }

  public static io.opensergo.proto.service_contract.v1.Node getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Node>
      PARSER = new com.google.protobuf.AbstractParser<Node>() {
    @java.lang.Override
    public Node parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Node(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Node> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Node> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.Node getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

