// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

/**
 * Protobuf type {@code opensergo.proto.service_contract.v1.ReportMetadataRequest}
 */
public final class ReportMetadataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.proto.service_contract.v1.ReportMetadataRequest)
    ReportMetadataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportMetadataRequest.newBuilder() to construct.
  private ReportMetadataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportMetadataRequest() {
    appName_ = "";
    serviceMetadata_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportMetadataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportMetadataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
          case 18: {
            io.opensergo.proto.service_contract.v1.Node.Builder subBuilder = null;
            if (node_ != null) {
              subBuilder = node_.toBuilder();
            }
            node_ = input.readMessage(io.opensergo.proto.service_contract.v1.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(node_);
              node_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              serviceMetadata_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.ServiceMetadata>();
              mutable_bitField0_ |= 0x00000001;
            }
            serviceMetadata_.add(
                input.readMessage(io.opensergo.proto.service_contract.v1.ServiceMetadata.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        serviceMetadata_ = java.util.Collections.unmodifiableList(serviceMetadata_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ReportMetadataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ReportMetadataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensergo.proto.service_contract.v1.ReportMetadataRequest.class, io.opensergo.proto.service_contract.v1.ReportMetadataRequest.Builder.class);
  }

  public static final int APP_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object appName_;
  /**
   * <code>string app_name = 1;</code>
   * @return The appName.
   */
  @java.lang.Override
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <code>string app_name = 1;</code>
   * @return The bytes for appName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_FIELD_NUMBER = 2;
  private io.opensergo.proto.service_contract.v1.Node node_;
  /**
   * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
   * @return Whether the node field is set.
   */
  @java.lang.Override
  public boolean hasNode() {
    return node_ != null;
  }
  /**
   * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
   * @return The node.
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.Node getNode() {
    return node_ == null ? io.opensergo.proto.service_contract.v1.Node.getDefaultInstance() : node_;
  }
  /**
   * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.NodeOrBuilder getNodeOrBuilder() {
    return getNode();
  }

  public static final int SERVICE_METADATA_FIELD_NUMBER = 3;
  private java.util.List<io.opensergo.proto.service_contract.v1.ServiceMetadata> serviceMetadata_;
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.opensergo.proto.service_contract.v1.ServiceMetadata> getServiceMetadataList() {
    return serviceMetadata_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder> 
      getServiceMetadataOrBuilderList() {
    return serviceMetadata_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
   */
  @java.lang.Override
  public int getServiceMetadataCount() {
    return serviceMetadata_.size();
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceMetadata getServiceMetadata(int index) {
    return serviceMetadata_.get(index);
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder getServiceMetadataOrBuilder(
      int index) {
    return serviceMetadata_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appName_);
    }
    if (node_ != null) {
      output.writeMessage(2, getNode());
    }
    for (int i = 0; i < serviceMetadata_.size(); i++) {
      output.writeMessage(3, serviceMetadata_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appName_);
    }
    if (node_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNode());
    }
    for (int i = 0; i < serviceMetadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, serviceMetadata_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensergo.proto.service_contract.v1.ReportMetadataRequest)) {
      return super.equals(obj);
    }
    io.opensergo.proto.service_contract.v1.ReportMetadataRequest other = (io.opensergo.proto.service_contract.v1.ReportMetadataRequest) obj;

    if (!getAppName()
        .equals(other.getAppName())) return false;
    if (hasNode() != other.hasNode()) return false;
    if (hasNode()) {
      if (!getNode()
          .equals(other.getNode())) return false;
    }
    if (!getServiceMetadataList()
        .equals(other.getServiceMetadataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    if (hasNode()) {
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
    }
    if (getServiceMetadataCount() > 0) {
      hash = (37 * hash) + SERVICE_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getServiceMetadataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensergo.proto.service_contract.v1.ReportMetadataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opensergo.proto.service_contract.v1.ReportMetadataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.proto.service_contract.v1.ReportMetadataRequest)
      io.opensergo.proto.service_contract.v1.ReportMetadataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ReportMetadataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ReportMetadataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensergo.proto.service_contract.v1.ReportMetadataRequest.class, io.opensergo.proto.service_contract.v1.ReportMetadataRequest.Builder.class);
    }

    // Construct using io.opensergo.proto.service_contract.v1.ReportMetadataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getServiceMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      appName_ = "";

      if (nodeBuilder_ == null) {
        node_ = null;
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }
      if (serviceMetadataBuilder_ == null) {
        serviceMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        serviceMetadataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ReportMetadataRequest_descriptor;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ReportMetadataRequest getDefaultInstanceForType() {
      return io.opensergo.proto.service_contract.v1.ReportMetadataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ReportMetadataRequest build() {
      io.opensergo.proto.service_contract.v1.ReportMetadataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ReportMetadataRequest buildPartial() {
      io.opensergo.proto.service_contract.v1.ReportMetadataRequest result = new io.opensergo.proto.service_contract.v1.ReportMetadataRequest(this);
      int from_bitField0_ = bitField0_;
      result.appName_ = appName_;
      if (nodeBuilder_ == null) {
        result.node_ = node_;
      } else {
        result.node_ = nodeBuilder_.build();
      }
      if (serviceMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          serviceMetadata_ = java.util.Collections.unmodifiableList(serviceMetadata_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.serviceMetadata_ = serviceMetadata_;
      } else {
        result.serviceMetadata_ = serviceMetadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensergo.proto.service_contract.v1.ReportMetadataRequest) {
        return mergeFrom((io.opensergo.proto.service_contract.v1.ReportMetadataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensergo.proto.service_contract.v1.ReportMetadataRequest other) {
      if (other == io.opensergo.proto.service_contract.v1.ReportMetadataRequest.getDefaultInstance()) return this;
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      if (other.hasNode()) {
        mergeNode(other.getNode());
      }
      if (serviceMetadataBuilder_ == null) {
        if (!other.serviceMetadata_.isEmpty()) {
          if (serviceMetadata_.isEmpty()) {
            serviceMetadata_ = other.serviceMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServiceMetadataIsMutable();
            serviceMetadata_.addAll(other.serviceMetadata_);
          }
          onChanged();
        }
      } else {
        if (!other.serviceMetadata_.isEmpty()) {
          if (serviceMetadataBuilder_.isEmpty()) {
            serviceMetadataBuilder_.dispose();
            serviceMetadataBuilder_ = null;
            serviceMetadata_ = other.serviceMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serviceMetadataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServiceMetadataFieldBuilder() : null;
          } else {
            serviceMetadataBuilder_.addAllMessages(other.serviceMetadata_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opensergo.proto.service_contract.v1.ReportMetadataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opensergo.proto.service_contract.v1.ReportMetadataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object appName_ = "";
    /**
     * <code>string app_name = 1;</code>
     * @return The appName.
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_name = 1;</code>
     * @return The bytes for appName.
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_name = 1;</code>
     * @param value The appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <code>string app_name = 1;</code>
     * @param value The bytes for appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }

    private io.opensergo.proto.service_contract.v1.Node node_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.Node, io.opensergo.proto.service_contract.v1.Node.Builder, io.opensergo.proto.service_contract.v1.NodeOrBuilder> nodeBuilder_;
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     * @return Whether the node field is set.
     */
    public boolean hasNode() {
      return nodeBuilder_ != null || node_ != null;
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     * @return The node.
     */
    public io.opensergo.proto.service_contract.v1.Node getNode() {
      if (nodeBuilder_ == null) {
        return node_ == null ? io.opensergo.proto.service_contract.v1.Node.getDefaultInstance() : node_;
      } else {
        return nodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public Builder setNode(io.opensergo.proto.service_contract.v1.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        node_ = value;
        onChanged();
      } else {
        nodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public Builder setNode(
        io.opensergo.proto.service_contract.v1.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        node_ = builderForValue.build();
        onChanged();
      } else {
        nodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public Builder mergeNode(io.opensergo.proto.service_contract.v1.Node value) {
      if (nodeBuilder_ == null) {
        if (node_ != null) {
          node_ =
            io.opensergo.proto.service_contract.v1.Node.newBuilder(node_).mergeFrom(value).buildPartial();
        } else {
          node_ = value;
        }
        onChanged();
      } else {
        nodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public Builder clearNode() {
      if (nodeBuilder_ == null) {
        node_ = null;
        onChanged();
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.Node.Builder getNodeBuilder() {
      
      onChanged();
      return getNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.NodeOrBuilder getNodeOrBuilder() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilder();
      } else {
        return node_ == null ?
            io.opensergo.proto.service_contract.v1.Node.getDefaultInstance() : node_;
      }
    }
    /**
     * <code>.opensergo.proto.service_contract.v1.Node node = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.Node, io.opensergo.proto.service_contract.v1.Node.Builder, io.opensergo.proto.service_contract.v1.NodeOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.Node, io.opensergo.proto.service_contract.v1.Node.Builder, io.opensergo.proto.service_contract.v1.NodeOrBuilder>(
                getNode(),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }

    private java.util.List<io.opensergo.proto.service_contract.v1.ServiceMetadata> serviceMetadata_ =
      java.util.Collections.emptyList();
    private void ensureServiceMetadataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        serviceMetadata_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.ServiceMetadata>(serviceMetadata_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.ServiceMetadata, io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder, io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder> serviceMetadataBuilder_;

    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.ServiceMetadata> getServiceMetadataList() {
      if (serviceMetadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(serviceMetadata_);
      } else {
        return serviceMetadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public int getServiceMetadataCount() {
      if (serviceMetadataBuilder_ == null) {
        return serviceMetadata_.size();
      } else {
        return serviceMetadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceMetadata getServiceMetadata(int index) {
      if (serviceMetadataBuilder_ == null) {
        return serviceMetadata_.get(index);
      } else {
        return serviceMetadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder setServiceMetadata(
        int index, io.opensergo.proto.service_contract.v1.ServiceMetadata value) {
      if (serviceMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceMetadataIsMutable();
        serviceMetadata_.set(index, value);
        onChanged();
      } else {
        serviceMetadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder setServiceMetadata(
        int index, io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder builderForValue) {
      if (serviceMetadataBuilder_ == null) {
        ensureServiceMetadataIsMutable();
        serviceMetadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceMetadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder addServiceMetadata(io.opensergo.proto.service_contract.v1.ServiceMetadata value) {
      if (serviceMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceMetadataIsMutable();
        serviceMetadata_.add(value);
        onChanged();
      } else {
        serviceMetadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder addServiceMetadata(
        int index, io.opensergo.proto.service_contract.v1.ServiceMetadata value) {
      if (serviceMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceMetadataIsMutable();
        serviceMetadata_.add(index, value);
        onChanged();
      } else {
        serviceMetadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder addServiceMetadata(
        io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder builderForValue) {
      if (serviceMetadataBuilder_ == null) {
        ensureServiceMetadataIsMutable();
        serviceMetadata_.add(builderForValue.build());
        onChanged();
      } else {
        serviceMetadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder addServiceMetadata(
        int index, io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder builderForValue) {
      if (serviceMetadataBuilder_ == null) {
        ensureServiceMetadataIsMutable();
        serviceMetadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceMetadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder addAllServiceMetadata(
        java.lang.Iterable<? extends io.opensergo.proto.service_contract.v1.ServiceMetadata> values) {
      if (serviceMetadataBuilder_ == null) {
        ensureServiceMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serviceMetadata_);
        onChanged();
      } else {
        serviceMetadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder clearServiceMetadata() {
      if (serviceMetadataBuilder_ == null) {
        serviceMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serviceMetadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public Builder removeServiceMetadata(int index) {
      if (serviceMetadataBuilder_ == null) {
        ensureServiceMetadataIsMutable();
        serviceMetadata_.remove(index);
        onChanged();
      } else {
        serviceMetadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder getServiceMetadataBuilder(
        int index) {
      return getServiceMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder getServiceMetadataOrBuilder(
        int index) {
      if (serviceMetadataBuilder_ == null) {
        return serviceMetadata_.get(index);  } else {
        return serviceMetadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public java.util.List<? extends io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder> 
         getServiceMetadataOrBuilderList() {
      if (serviceMetadataBuilder_ != null) {
        return serviceMetadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(serviceMetadata_);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder addServiceMetadataBuilder() {
      return getServiceMetadataFieldBuilder().addBuilder(
          io.opensergo.proto.service_contract.v1.ServiceMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder addServiceMetadataBuilder(
        int index) {
      return getServiceMetadataFieldBuilder().addBuilder(
          index, io.opensergo.proto.service_contract.v1.ServiceMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceMetadata service_metadata = 3;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder> 
         getServiceMetadataBuilderList() {
      return getServiceMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.ServiceMetadata, io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder, io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder> 
        getServiceMetadataFieldBuilder() {
      if (serviceMetadataBuilder_ == null) {
        serviceMetadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.ServiceMetadata, io.opensergo.proto.service_contract.v1.ServiceMetadata.Builder, io.opensergo.proto.service_contract.v1.ServiceMetadataOrBuilder>(
                serviceMetadata_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        serviceMetadata_ = null;
      }
      return serviceMetadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.proto.service_contract.v1.ReportMetadataRequest)
  }

  // @@protoc_insertion_point(class_scope:opensergo.proto.service_contract.v1.ReportMetadataRequest)
  private static final io.opensergo.proto.service_contract.v1.ReportMetadataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensergo.proto.service_contract.v1.ReportMetadataRequest();
  }

  public static io.opensergo.proto.service_contract.v1.ReportMetadataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportMetadataRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReportMetadataRequest>() {
    @java.lang.Override
    public ReportMetadataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportMetadataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportMetadataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportMetadataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ReportMetadataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

