// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

/**
 * <pre>
 * Describes a service.
 * </pre>
 *
 * Protobuf type {@code opensergo.proto.service_contract.v1.ServiceDescriptor}
 */
public final class ServiceDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.proto.service_contract.v1.ServiceDescriptor)
    ServiceDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceDescriptor.newBuilder() to construct.
  private ServiceDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceDescriptor() {
    name_ = "";
    methods_ = java.util.Collections.emptyList();
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceDescriptor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              methods_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.MethodDescriptor>();
              mutable_bitField0_ |= 0x00000001;
            }
            methods_.add(
                input.readMessage(io.opensergo.proto.service_contract.v1.MethodDescriptor.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            description_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        methods_ = java.util.Collections.unmodifiableList(methods_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceDescriptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensergo.proto.service_contract.v1.ServiceDescriptor.class, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODS_FIELD_NUMBER = 2;
  private java.util.List<io.opensergo.proto.service_contract.v1.MethodDescriptor> methods_;
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.opensergo.proto.service_contract.v1.MethodDescriptor> getMethodsList() {
    return methods_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder> 
      getMethodsOrBuilderList() {
    return methods_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
   */
  @java.lang.Override
  public int getMethodsCount() {
    return methods_.size();
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.MethodDescriptor getMethods(int index) {
    return methods_.get(index);
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder getMethodsOrBuilder(
      int index) {
    return methods_.get(index);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * description of this service
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * description of this service
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * description of this service
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      output.writeMessage(2, methods_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, methods_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensergo.proto.service_contract.v1.ServiceDescriptor)) {
      return super.equals(obj);
    }
    io.opensergo.proto.service_contract.v1.ServiceDescriptor other = (io.opensergo.proto.service_contract.v1.ServiceDescriptor) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getMethodsList()
        .equals(other.getMethodsList())) return false;
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getMethodsCount() > 0) {
      hash = (37 * hash) + METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodsList().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensergo.proto.service_contract.v1.ServiceDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Describes a service.
   * </pre>
   *
   * Protobuf type {@code opensergo.proto.service_contract.v1.ServiceDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.proto.service_contract.v1.ServiceDescriptor)
      io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensergo.proto.service_contract.v1.ServiceDescriptor.class, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder.class);
    }

    // Construct using io.opensergo.proto.service_contract.v1.ServiceDescriptor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMethodsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        methodsBuilder_.clear();
      }
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceDescriptor_descriptor;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor getDefaultInstanceForType() {
      return io.opensergo.proto.service_contract.v1.ServiceDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor build() {
      io.opensergo.proto.service_contract.v1.ServiceDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor buildPartial() {
      io.opensergo.proto.service_contract.v1.ServiceDescriptor result = new io.opensergo.proto.service_contract.v1.ServiceDescriptor(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (methodsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.methods_ = methods_;
      } else {
        result.methods_ = methodsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.description_ = description_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensergo.proto.service_contract.v1.ServiceDescriptor) {
        return mergeFrom((io.opensergo.proto.service_contract.v1.ServiceDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensergo.proto.service_contract.v1.ServiceDescriptor other) {
      if (other == io.opensergo.proto.service_contract.v1.ServiceDescriptor.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (methodsBuilder_ == null) {
        if (!other.methods_.isEmpty()) {
          if (methods_.isEmpty()) {
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMethodsIsMutable();
            methods_.addAll(other.methods_);
          }
          onChanged();
        }
      } else {
        if (!other.methods_.isEmpty()) {
          if (methodsBuilder_.isEmpty()) {
            methodsBuilder_.dispose();
            methodsBuilder_ = null;
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000001);
            methodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMethodsFieldBuilder() : null;
          } else {
            methodsBuilder_.addAllMessages(other.methods_);
          }
        }
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000002;
        description_ = other.description_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opensergo.proto.service_contract.v1.ServiceDescriptor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opensergo.proto.service_contract.v1.ServiceDescriptor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.opensergo.proto.service_contract.v1.MethodDescriptor> methods_ =
      java.util.Collections.emptyList();
    private void ensureMethodsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        methods_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.MethodDescriptor>(methods_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.MethodDescriptor, io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder, io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder> methodsBuilder_;

    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.MethodDescriptor> getMethodsList() {
      if (methodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(methods_);
      } else {
        return methodsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public int getMethodsCount() {
      if (methodsBuilder_ == null) {
        return methods_.size();
      } else {
        return methodsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.MethodDescriptor getMethods(int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);
      } else {
        return methodsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder setMethods(
        int index, io.opensergo.proto.service_contract.v1.MethodDescriptor value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.set(index, value);
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder setMethods(
        int index, io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder addMethods(io.opensergo.proto.service_contract.v1.MethodDescriptor value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder addMethods(
        int index, io.opensergo.proto.service_contract.v1.MethodDescriptor value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(index, value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder addMethods(
        io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder addMethods(
        int index, io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder addAllMethods(
        java.lang.Iterable<? extends io.opensergo.proto.service_contract.v1.MethodDescriptor> values) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methods_);
        onChanged();
      } else {
        methodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder clearMethods() {
      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        methodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public Builder removeMethods(int index) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.remove(index);
        onChanged();
      } else {
        methodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder getMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder getMethodsOrBuilder(
        int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);  } else {
        return methodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public java.util.List<? extends io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder> 
         getMethodsOrBuilderList() {
      if (methodsBuilder_ != null) {
        return methodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(methods_);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder addMethodsBuilder() {
      return getMethodsFieldBuilder().addBuilder(
          io.opensergo.proto.service_contract.v1.MethodDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder addMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().addBuilder(
          index, io.opensergo.proto.service_contract.v1.MethodDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.MethodDescriptor methods = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder> 
         getMethodsBuilderList() {
      return getMethodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.MethodDescriptor, io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder, io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder> 
        getMethodsFieldBuilder() {
      if (methodsBuilder_ == null) {
        methodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.MethodDescriptor, io.opensergo.proto.service_contract.v1.MethodDescriptor.Builder, io.opensergo.proto.service_contract.v1.MethodDescriptorOrBuilder>(
                methods_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        methods_ = null;
      }
      return methodsBuilder_;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000002);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * description of this service
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      description_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.proto.service_contract.v1.ServiceDescriptor)
  }

  // @@protoc_insertion_point(class_scope:opensergo.proto.service_contract.v1.ServiceDescriptor)
  private static final io.opensergo.proto.service_contract.v1.ServiceDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensergo.proto.service_contract.v1.ServiceDescriptor();
  }

  public static io.opensergo.proto.service_contract.v1.ServiceDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<ServiceDescriptor>() {
    @java.lang.Override
    public ServiceDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceDescriptor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

