// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

/**
 * Protobuf type {@code opensergo.proto.service_contract.v1.ServiceContract}
 */
public final class ServiceContract extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.proto.service_contract.v1.ServiceContract)
    ServiceContractOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceContract.newBuilder() to construct.
  private ServiceContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceContract() {
    services_ = java.util.Collections.emptyList();
    types_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceContract();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceContract(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              services_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.ServiceDescriptor>();
              mutable_bitField0_ |= 0x00000001;
            }
            services_.add(
                input.readMessage(io.opensergo.proto.service_contract.v1.ServiceDescriptor.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              types_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.TypeDescriptor>();
              mutable_bitField0_ |= 0x00000002;
            }
            types_.add(
                input.readMessage(io.opensergo.proto.service_contract.v1.TypeDescriptor.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        services_ = java.util.Collections.unmodifiableList(services_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        types_ = java.util.Collections.unmodifiableList(types_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceContract_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceContract_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opensergo.proto.service_contract.v1.ServiceContract.class, io.opensergo.proto.service_contract.v1.ServiceContract.Builder.class);
  }

  public static final int SERVICES_FIELD_NUMBER = 1;
  private java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor> services_;
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor> getServicesList() {
    return services_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder> 
      getServicesOrBuilderList() {
    return services_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  @java.lang.Override
  public int getServicesCount() {
    return services_.size();
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceDescriptor getServices(int index) {
    return services_.get(index);
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder getServicesOrBuilder(
      int index) {
    return services_.get(index);
  }

  public static final int TYPES_FIELD_NUMBER = 2;
  private java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor> types_;
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor> getTypesList() {
    return types_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder> 
      getTypesOrBuilderList() {
    return types_;
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  @java.lang.Override
  public int getTypesCount() {
    return types_.size();
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.TypeDescriptor getTypes(int index) {
    return types_.get(index);
  }
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder getTypesOrBuilder(
      int index) {
    return types_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < services_.size(); i++) {
      output.writeMessage(1, services_.get(i));
    }
    for (int i = 0; i < types_.size(); i++) {
      output.writeMessage(2, types_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < services_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, services_.get(i));
    }
    for (int i = 0; i < types_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, types_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opensergo.proto.service_contract.v1.ServiceContract)) {
      return super.equals(obj);
    }
    io.opensergo.proto.service_contract.v1.ServiceContract other = (io.opensergo.proto.service_contract.v1.ServiceContract) obj;

    if (!getServicesList()
        .equals(other.getServicesList())) return false;
    if (!getTypesList()
        .equals(other.getTypesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServicesCount() > 0) {
      hash = (37 * hash) + SERVICES_FIELD_NUMBER;
      hash = (53 * hash) + getServicesList().hashCode();
    }
    if (getTypesCount() > 0) {
      hash = (37 * hash) + TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTypesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opensergo.proto.service_contract.v1.ServiceContract parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opensergo.proto.service_contract.v1.ServiceContract prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opensergo.proto.service_contract.v1.ServiceContract}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.proto.service_contract.v1.ServiceContract)
      io.opensergo.proto.service_contract.v1.ServiceContractOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opensergo.proto.service_contract.v1.ServiceContract.class, io.opensergo.proto.service_contract.v1.ServiceContract.Builder.class);
    }

    // Construct using io.opensergo.proto.service_contract.v1.ServiceContract.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getServicesFieldBuilder();
        getTypesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (servicesBuilder_ == null) {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        servicesBuilder_.clear();
      }
      if (typesBuilder_ == null) {
        types_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        typesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContractProto.internal_static_opensergo_proto_service_contract_v1_ServiceContract_descriptor;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceContract getDefaultInstanceForType() {
      return io.opensergo.proto.service_contract.v1.ServiceContract.getDefaultInstance();
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceContract build() {
      io.opensergo.proto.service_contract.v1.ServiceContract result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opensergo.proto.service_contract.v1.ServiceContract buildPartial() {
      io.opensergo.proto.service_contract.v1.ServiceContract result = new io.opensergo.proto.service_contract.v1.ServiceContract(this);
      int from_bitField0_ = bitField0_;
      if (servicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          services_ = java.util.Collections.unmodifiableList(services_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.services_ = services_;
      } else {
        result.services_ = servicesBuilder_.build();
      }
      if (typesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          types_ = java.util.Collections.unmodifiableList(types_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.types_ = types_;
      } else {
        result.types_ = typesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opensergo.proto.service_contract.v1.ServiceContract) {
        return mergeFrom((io.opensergo.proto.service_contract.v1.ServiceContract)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opensergo.proto.service_contract.v1.ServiceContract other) {
      if (other == io.opensergo.proto.service_contract.v1.ServiceContract.getDefaultInstance()) return this;
      if (servicesBuilder_ == null) {
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
      } else {
        if (!other.services_.isEmpty()) {
          if (servicesBuilder_.isEmpty()) {
            servicesBuilder_.dispose();
            servicesBuilder_ = null;
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000001);
            servicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServicesFieldBuilder() : null;
          } else {
            servicesBuilder_.addAllMessages(other.services_);
          }
        }
      }
      if (typesBuilder_ == null) {
        if (!other.types_.isEmpty()) {
          if (types_.isEmpty()) {
            types_ = other.types_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTypesIsMutable();
            types_.addAll(other.types_);
          }
          onChanged();
        }
      } else {
        if (!other.types_.isEmpty()) {
          if (typesBuilder_.isEmpty()) {
            typesBuilder_.dispose();
            typesBuilder_ = null;
            types_ = other.types_;
            bitField0_ = (bitField0_ & ~0x00000002);
            typesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTypesFieldBuilder() : null;
          } else {
            typesBuilder_.addAllMessages(other.types_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opensergo.proto.service_contract.v1.ServiceContract parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opensergo.proto.service_contract.v1.ServiceContract) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor> services_ =
      java.util.Collections.emptyList();
    private void ensureServicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        services_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.ServiceDescriptor>(services_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.ServiceDescriptor, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder, io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder> servicesBuilder_;

    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor> getServicesList() {
      if (servicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(services_);
      } else {
        return servicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public int getServicesCount() {
      if (servicesBuilder_ == null) {
        return services_.size();
      } else {
        return servicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor getServices(int index) {
      if (servicesBuilder_ == null) {
        return services_.get(index);
      } else {
        return servicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder setServices(
        int index, io.opensergo.proto.service_contract.v1.ServiceDescriptor value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
      } else {
        servicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder setServices(
        int index, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.set(index, builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder addServices(io.opensergo.proto.service_contract.v1.ServiceDescriptor value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.add(value);
        onChanged();
      } else {
        servicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder addServices(
        int index, io.opensergo.proto.service_contract.v1.ServiceDescriptor value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.add(index, value);
        onChanged();
      } else {
        servicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder addServices(
        io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.add(builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder addServices(
        int index, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.add(index, builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder addAllServices(
        java.lang.Iterable<? extends io.opensergo.proto.service_contract.v1.ServiceDescriptor> values) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, services_);
        onChanged();
      } else {
        servicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder clearServices() {
      if (servicesBuilder_ == null) {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        servicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public Builder removeServices(int index) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.remove(index);
        onChanged();
      } else {
        servicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder getServicesBuilder(
        int index) {
      return getServicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder getServicesOrBuilder(
        int index) {
      if (servicesBuilder_ == null) {
        return services_.get(index);  } else {
        return servicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public java.util.List<? extends io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder> 
         getServicesOrBuilderList() {
      if (servicesBuilder_ != null) {
        return servicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(services_);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder addServicesBuilder() {
      return getServicesFieldBuilder().addBuilder(
          io.opensergo.proto.service_contract.v1.ServiceDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder addServicesBuilder(
        int index) {
      return getServicesFieldBuilder().addBuilder(
          index, io.opensergo.proto.service_contract.v1.ServiceDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder> 
         getServicesBuilderList() {
      return getServicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.ServiceDescriptor, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder, io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder> 
        getServicesFieldBuilder() {
      if (servicesBuilder_ == null) {
        servicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.ServiceDescriptor, io.opensergo.proto.service_contract.v1.ServiceDescriptor.Builder, io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder>(
                services_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        services_ = null;
      }
      return servicesBuilder_;
    }

    private java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor> types_ =
      java.util.Collections.emptyList();
    private void ensureTypesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        types_ = new java.util.ArrayList<io.opensergo.proto.service_contract.v1.TypeDescriptor>(types_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.TypeDescriptor, io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder, io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder> typesBuilder_;

    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor> getTypesList() {
      if (typesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(types_);
      } else {
        return typesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public int getTypesCount() {
      if (typesBuilder_ == null) {
        return types_.size();
      } else {
        return typesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.TypeDescriptor getTypes(int index) {
      if (typesBuilder_ == null) {
        return types_.get(index);
      } else {
        return typesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder setTypes(
        int index, io.opensergo.proto.service_contract.v1.TypeDescriptor value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.set(index, value);
        onChanged();
      } else {
        typesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder setTypes(
        int index, io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.set(index, builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder addTypes(io.opensergo.proto.service_contract.v1.TypeDescriptor value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.add(value);
        onChanged();
      } else {
        typesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder addTypes(
        int index, io.opensergo.proto.service_contract.v1.TypeDescriptor value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.add(index, value);
        onChanged();
      } else {
        typesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder addTypes(
        io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.add(builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder addTypes(
        int index, io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.add(index, builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder addAllTypes(
        java.lang.Iterable<? extends io.opensergo.proto.service_contract.v1.TypeDescriptor> values) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, types_);
        onChanged();
      } else {
        typesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder clearTypes() {
      if (typesBuilder_ == null) {
        types_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        typesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public Builder removeTypes(int index) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.remove(index);
        onChanged();
      } else {
        typesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder getTypesBuilder(
        int index) {
      return getTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder getTypesOrBuilder(
        int index) {
      if (typesBuilder_ == null) {
        return types_.get(index);  } else {
        return typesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public java.util.List<? extends io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder> 
         getTypesOrBuilderList() {
      if (typesBuilder_ != null) {
        return typesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(types_);
      }
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder addTypesBuilder() {
      return getTypesFieldBuilder().addBuilder(
          io.opensergo.proto.service_contract.v1.TypeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder addTypesBuilder(
        int index) {
      return getTypesFieldBuilder().addBuilder(
          index, io.opensergo.proto.service_contract.v1.TypeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
     */
    public java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder> 
         getTypesBuilderList() {
      return getTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opensergo.proto.service_contract.v1.TypeDescriptor, io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder, io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder> 
        getTypesFieldBuilder() {
      if (typesBuilder_ == null) {
        typesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opensergo.proto.service_contract.v1.TypeDescriptor, io.opensergo.proto.service_contract.v1.TypeDescriptor.Builder, io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder>(
                types_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        types_ = null;
      }
      return typesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.proto.service_contract.v1.ServiceContract)
  }

  // @@protoc_insertion_point(class_scope:opensergo.proto.service_contract.v1.ServiceContract)
  private static final io.opensergo.proto.service_contract.v1.ServiceContract DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opensergo.proto.service_contract.v1.ServiceContract();
  }

  public static io.opensergo.proto.service_contract.v1.ServiceContract getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceContract>
      PARSER = new com.google.protobuf.AbstractParser<ServiceContract>() {
    @java.lang.Override
    public ServiceContract parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceContract(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceContract> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceContract> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opensergo.proto.service_contract.v1.ServiceContract getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

