// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opensergo/proto/service_contract/v1/service_contract.proto

package io.opensergo.proto.service_contract.v1;

public interface ServiceContractOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.proto.service_contract.v1.ServiceContract)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  java.util.List<io.opensergo.proto.service_contract.v1.ServiceDescriptor> 
      getServicesList();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  io.opensergo.proto.service_contract.v1.ServiceDescriptor getServices(int index);
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  java.util.List<? extends io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.ServiceDescriptor services = 1;</code>
   */
  io.opensergo.proto.service_contract.v1.ServiceDescriptorOrBuilder getServicesOrBuilder(
      int index);

  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  java.util.List<io.opensergo.proto.service_contract.v1.TypeDescriptor> 
      getTypesList();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  io.opensergo.proto.service_contract.v1.TypeDescriptor getTypes(int index);
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  java.util.List<? extends io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder> 
      getTypesOrBuilderList();
  /**
   * <code>repeated .opensergo.proto.service_contract.v1.TypeDescriptor types = 2;</code>
   */
  io.opensergo.proto.service_contract.v1.TypeDescriptorOrBuilder getTypesOrBuilder(
      int index);
}
