// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public interface MessageOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.api.MessageOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Is this message deprecated?
   * Depending on the target platform, this can emit Deprecated annotations
   * for the message, or it will be completely ignored; in the very least,
   * this is a formalization for deprecating messages.
   * </pre>
   *
   * <code>optional bool deprecated = 3;</code>
   * @return Whether the deprecated field is set.
   */
  boolean hasDeprecated();
  /**
   * <pre>
   * Is this message deprecated?
   * Depending on the target platform, this can emit Deprecated annotations
   * for the message, or it will be completely ignored; in the very least,
   * this is a formalization for deprecating messages.
   * </pre>
   *
   * <code>optional bool deprecated = 3;</code>
   * @return The deprecated.
   */
  boolean getDeprecated();
}
