// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public interface ReportMetadataReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.api.ReportMetadataReply)
    com.google.protobuf.MessageOrBuilder {
}
