// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public interface ReportMetadataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.api.ReportMetadataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.opensergo.api.ServiceContractProto serviceContract = 1;</code>
   * @return Whether the serviceContract field is set.
   */
  boolean hasServiceContract();
  /**
   * <code>.opensergo.api.ServiceContractProto serviceContract = 1;</code>
   * @return The serviceContract.
   */
  com.alibaba.opensergo.api.proto.ServiceContractProto getServiceContract();
  /**
   * <code>.opensergo.api.ServiceContractProto serviceContract = 1;</code>
   */
  com.alibaba.opensergo.api.proto.ServiceContractProtoOrBuilder getServiceContractOrBuilder();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
