// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public interface ServiceDescriptorProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.api.ServiceDescriptorProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto> 
      getMethodList();
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  com.alibaba.opensergo.api.proto.MethodDescriptorProto getMethod(int index);
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  int getMethodCount();
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  java.util.List<? extends com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder> 
      getMethodOrBuilderList();
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder getMethodOrBuilder(
      int index);

  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   * @return The options.
   */
  com.alibaba.opensergo.api.proto.ServiceOptions getOptions();
  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   */
  com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder getOptionsOrBuilder();

  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
