// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

/**
 * <pre>
 * Describes a service.
 * </pre>
 *
 * Protobuf type {@code opensergo.api.ServiceDescriptorProto}
 */
public final class ServiceDescriptorProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opensergo.api.ServiceDescriptorProto)
    ServiceDescriptorProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceDescriptorProto.newBuilder() to construct.
  private ServiceDescriptorProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceDescriptorProto() {
    name_ = "";
    method_ = java.util.Collections.emptyList();
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceDescriptorProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceDescriptorProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              method_ = new java.util.ArrayList<com.alibaba.opensergo.api.proto.MethodDescriptorProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            method_.add(
                input.readMessage(com.alibaba.opensergo.api.proto.MethodDescriptorProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.alibaba.opensergo.api.proto.ServiceOptions.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = options_.toBuilder();
            }
            options_ = input.readMessage(com.alibaba.opensergo.api.proto.ServiceOptions.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(options_);
              options_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            description_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        method_ = java.util.Collections.unmodifiableList(method_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.opensergo.api.proto.Servicecontract.internal_static_opensergo_api_ServiceDescriptorProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.opensergo.api.proto.Servicecontract.internal_static_opensergo_api_ServiceDescriptorProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.opensergo.api.proto.ServiceDescriptorProto.class, com.alibaba.opensergo.api.proto.ServiceDescriptorProto.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  private java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto> method_;
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto> getMethodList() {
    return method_;
  }
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder> 
      getMethodOrBuilderList() {
    return method_;
  }
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  @java.lang.Override
  public int getMethodCount() {
    return method_.size();
  }
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  @java.lang.Override
  public com.alibaba.opensergo.api.proto.MethodDescriptorProto getMethod(int index) {
    return method_.get(index);
  }
  /**
   * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
   */
  @java.lang.Override
  public com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder getMethodOrBuilder(
      int index) {
    return method_.get(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private com.alibaba.opensergo.api.proto.ServiceOptions options_;
  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   * @return Whether the options field is set.
   */
  @java.lang.Override
  public boolean hasOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   * @return The options.
   */
  @java.lang.Override
  public com.alibaba.opensergo.api.proto.ServiceOptions getOptions() {
    return options_ == null ? com.alibaba.opensergo.api.proto.ServiceOptions.getDefaultInstance() : options_;
  }
  /**
   * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
   */
  @java.lang.Override
  public com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder getOptionsOrBuilder() {
    return options_ == null ? com.alibaba.opensergo.api.proto.ServiceOptions.getDefaultInstance() : options_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 注释/注解
   * </pre>
   *
   * <code>optional string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < method_.size(); i++) {
      output.writeMessage(2, method_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < method_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, method_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.opensergo.api.proto.ServiceDescriptorProto)) {
      return super.equals(obj);
    }
    com.alibaba.opensergo.api.proto.ServiceDescriptorProto other = (com.alibaba.opensergo.api.proto.ServiceDescriptorProto) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!getMethodList()
        .equals(other.getMethodList())) return false;
    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions()
          .equals(other.getOptions())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (getMethodCount() > 0) {
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethodList().hashCode();
    }
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.opensergo.api.proto.ServiceDescriptorProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Describes a service.
   * </pre>
   *
   * Protobuf type {@code opensergo.api.ServiceDescriptorProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opensergo.api.ServiceDescriptorProto)
      com.alibaba.opensergo.api.proto.ServiceDescriptorProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.opensergo.api.proto.Servicecontract.internal_static_opensergo_api_ServiceDescriptorProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.opensergo.api.proto.Servicecontract.internal_static_opensergo_api_ServiceDescriptorProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.opensergo.api.proto.ServiceDescriptorProto.class, com.alibaba.opensergo.api.proto.ServiceDescriptorProto.Builder.class);
    }

    // Construct using com.alibaba.opensergo.api.proto.ServiceDescriptorProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMethodFieldBuilder();
        getOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (methodBuilder_ == null) {
        method_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        methodBuilder_.clear();
      }
      if (optionsBuilder_ == null) {
        options_ = null;
      } else {
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.opensergo.api.proto.Servicecontract.internal_static_opensergo_api_ServiceDescriptorProto_descriptor;
    }

    @java.lang.Override
    public com.alibaba.opensergo.api.proto.ServiceDescriptorProto getDefaultInstanceForType() {
      return com.alibaba.opensergo.api.proto.ServiceDescriptorProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.alibaba.opensergo.api.proto.ServiceDescriptorProto build() {
      com.alibaba.opensergo.api.proto.ServiceDescriptorProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alibaba.opensergo.api.proto.ServiceDescriptorProto buildPartial() {
      com.alibaba.opensergo.api.proto.ServiceDescriptorProto result = new com.alibaba.opensergo.api.proto.ServiceDescriptorProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (methodBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          method_ = java.util.Collections.unmodifiableList(method_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.method_ = method_;
      } else {
        result.method_ = methodBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (optionsBuilder_ == null) {
          result.options_ = options_;
        } else {
          result.options_ = optionsBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.description_ = description_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.opensergo.api.proto.ServiceDescriptorProto) {
        return mergeFrom((com.alibaba.opensergo.api.proto.ServiceDescriptorProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.opensergo.api.proto.ServiceDescriptorProto other) {
      if (other == com.alibaba.opensergo.api.proto.ServiceDescriptorProto.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (methodBuilder_ == null) {
        if (!other.method_.isEmpty()) {
          if (method_.isEmpty()) {
            method_ = other.method_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMethodIsMutable();
            method_.addAll(other.method_);
          }
          onChanged();
        }
      } else {
        if (!other.method_.isEmpty()) {
          if (methodBuilder_.isEmpty()) {
            methodBuilder_.dispose();
            methodBuilder_ = null;
            method_ = other.method_;
            bitField0_ = (bitField0_ & ~0x00000002);
            methodBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMethodFieldBuilder() : null;
          } else {
            methodBuilder_.addAllMessages(other.method_);
          }
        }
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000008;
        description_ = other.description_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.opensergo.api.proto.ServiceDescriptorProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.opensergo.api.proto.ServiceDescriptorProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto> method_ =
      java.util.Collections.emptyList();
    private void ensureMethodIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        method_ = new java.util.ArrayList<com.alibaba.opensergo.api.proto.MethodDescriptorProto>(method_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.alibaba.opensergo.api.proto.MethodDescriptorProto, com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder, com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder> methodBuilder_;

    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto> getMethodList() {
      if (methodBuilder_ == null) {
        return java.util.Collections.unmodifiableList(method_);
      } else {
        return methodBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public int getMethodCount() {
      if (methodBuilder_ == null) {
        return method_.size();
      } else {
        return methodBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public com.alibaba.opensergo.api.proto.MethodDescriptorProto getMethod(int index) {
      if (methodBuilder_ == null) {
        return method_.get(index);
      } else {
        return methodBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder setMethod(
        int index, com.alibaba.opensergo.api.proto.MethodDescriptorProto value) {
      if (methodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodIsMutable();
        method_.set(index, value);
        onChanged();
      } else {
        methodBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder setMethod(
        int index, com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder builderForValue) {
      if (methodBuilder_ == null) {
        ensureMethodIsMutable();
        method_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder addMethod(com.alibaba.opensergo.api.proto.MethodDescriptorProto value) {
      if (methodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodIsMutable();
        method_.add(value);
        onChanged();
      } else {
        methodBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder addMethod(
        int index, com.alibaba.opensergo.api.proto.MethodDescriptorProto value) {
      if (methodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodIsMutable();
        method_.add(index, value);
        onChanged();
      } else {
        methodBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder addMethod(
        com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder builderForValue) {
      if (methodBuilder_ == null) {
        ensureMethodIsMutable();
        method_.add(builderForValue.build());
        onChanged();
      } else {
        methodBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder addMethod(
        int index, com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder builderForValue) {
      if (methodBuilder_ == null) {
        ensureMethodIsMutable();
        method_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder addAllMethod(
        java.lang.Iterable<? extends com.alibaba.opensergo.api.proto.MethodDescriptorProto> values) {
      if (methodBuilder_ == null) {
        ensureMethodIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, method_);
        onChanged();
      } else {
        methodBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder clearMethod() {
      if (methodBuilder_ == null) {
        method_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        methodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public Builder removeMethod(int index) {
      if (methodBuilder_ == null) {
        ensureMethodIsMutable();
        method_.remove(index);
        onChanged();
      } else {
        methodBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder getMethodBuilder(
        int index) {
      return getMethodFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder getMethodOrBuilder(
        int index) {
      if (methodBuilder_ == null) {
        return method_.get(index);  } else {
        return methodBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public java.util.List<? extends com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder> 
         getMethodOrBuilderList() {
      if (methodBuilder_ != null) {
        return methodBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(method_);
      }
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder addMethodBuilder() {
      return getMethodFieldBuilder().addBuilder(
          com.alibaba.opensergo.api.proto.MethodDescriptorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder addMethodBuilder(
        int index) {
      return getMethodFieldBuilder().addBuilder(
          index, com.alibaba.opensergo.api.proto.MethodDescriptorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .opensergo.api.MethodDescriptorProto method = 2;</code>
     */
    public java.util.List<com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder> 
         getMethodBuilderList() {
      return getMethodFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.alibaba.opensergo.api.proto.MethodDescriptorProto, com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder, com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder> 
        getMethodFieldBuilder() {
      if (methodBuilder_ == null) {
        methodBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.alibaba.opensergo.api.proto.MethodDescriptorProto, com.alibaba.opensergo.api.proto.MethodDescriptorProto.Builder, com.alibaba.opensergo.api.proto.MethodDescriptorProtoOrBuilder>(
                method_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        method_ = null;
      }
      return methodBuilder_;
    }

    private com.alibaba.opensergo.api.proto.ServiceOptions options_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alibaba.opensergo.api.proto.ServiceOptions, com.alibaba.opensergo.api.proto.ServiceOptions.Builder, com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder> optionsBuilder_;
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     * @return The options.
     */
    public com.alibaba.opensergo.api.proto.ServiceOptions getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? com.alibaba.opensergo.api.proto.ServiceOptions.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public Builder setOptions(com.alibaba.opensergo.api.proto.ServiceOptions value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
        onChanged();
      } else {
        optionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public Builder setOptions(
        com.alibaba.opensergo.api.proto.ServiceOptions.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
        onChanged();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public Builder mergeOptions(com.alibaba.opensergo.api.proto.ServiceOptions value) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            options_ != null &&
            options_ != com.alibaba.opensergo.api.proto.ServiceOptions.getDefaultInstance()) {
          options_ =
            com.alibaba.opensergo.api.proto.ServiceOptions.newBuilder(options_).mergeFrom(value).buildPartial();
        } else {
          options_ = value;
        }
        onChanged();
      } else {
        optionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = null;
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public com.alibaba.opensergo.api.proto.ServiceOptions.Builder getOptionsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    public com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ?
            com.alibaba.opensergo.api.proto.ServiceOptions.getDefaultInstance() : options_;
      }
    }
    /**
     * <code>optional .opensergo.api.ServiceOptions options = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alibaba.opensergo.api.proto.ServiceOptions, com.alibaba.opensergo.api.proto.ServiceOptions.Builder, com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.alibaba.opensergo.api.proto.ServiceOptions, com.alibaba.opensergo.api.proto.ServiceOptions.Builder, com.alibaba.opensergo.api.proto.ServiceOptionsOrBuilder>(
                getOptions(),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000008);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 注释/注解
     * </pre>
     *
     * <code>optional string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      description_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opensergo.api.ServiceDescriptorProto)
  }

  // @@protoc_insertion_point(class_scope:opensergo.api.ServiceDescriptorProto)
  private static final com.alibaba.opensergo.api.proto.ServiceDescriptorProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.opensergo.api.proto.ServiceDescriptorProto();
  }

  public static com.alibaba.opensergo.api.proto.ServiceDescriptorProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceDescriptorProto>
      PARSER = new com.google.protobuf.AbstractParser<ServiceDescriptorProto>() {
    @java.lang.Override
    public ServiceDescriptorProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceDescriptorProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceDescriptorProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceDescriptorProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alibaba.opensergo.api.proto.ServiceDescriptorProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

