// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public final class Servicecontract {
  private Servicecontract() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_ReportMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_ReportMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_ReportMetadataReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_ReportMetadataReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_ServiceContractProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_ServiceContractProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_ServiceDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_ServiceDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_MethodDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_MethodDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_ServiceOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_ServiceOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_MethodOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_MethodOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_UninterpretedOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_UninterpretedOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_UninterpretedOption_NamePart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_UninterpretedOption_NamePart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_OneofDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_OneofDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_DescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_DescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_DescriptorProto_ReservedRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_DescriptorProto_ReservedRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_EnumDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_EnumDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_EnumValueDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_EnumValueDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_EnumValueOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_EnumValueOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_MessageOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_MessageOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_FieldDescriptorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_FieldDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opensergo_api_FieldOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opensergo_api_FieldOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)specification/proto/servicecontract.pr" +
      "oto\022\ropensergo.api\"c\n\025ReportMetadataRequ" +
      "est\022<\n\017serviceContract\030\001 \001(\0132#.opensergo" +
      ".api.ServiceContractProto\022\014\n\004name\030\002 \001(\t\"" +
      "\025\n\023ReportMetadataReply\"~\n\024ServiceContrac" +
      "tProto\022-\n\005types\030\004 \003(\0132\036.opensergo.api.De" +
      "scriptorProto\0227\n\010services\030\006 \003(\0132%.opense" +
      "rgo.api.ServiceDescriptorProto\"\325\001\n\026Servi" +
      "ceDescriptorProto\022\021\n\004name\030\001 \001(\tH\000\210\001\001\0224\n\006" +
      "method\030\002 \003(\0132$.opensergo.api.MethodDescr" +
      "iptorProto\0223\n\007options\030\003 \001(\0132\035.opensergo." +
      "api.ServiceOptionsH\001\210\001\001\022\030\n\013description\030\004" +
      " \001(\tH\002\210\001\001B\007\n\005_nameB\n\n\010_optionsB\016\n\014_descr" +
      "iption\"\375\002\n\025MethodDescriptorProto\022\021\n\004name" +
      "\030\001 \001(\tH\000\210\001\001\022\027\n\ninput_type\030\002 \001(\tH\001\210\001\001\022\030\n\013" +
      "output_type\030\003 \001(\tH\002\210\001\001\0222\n\007options\030\004 \001(\0132" +
      "\034.opensergo.api.MethodOptionsH\003\210\001\001\022\035\n\020cl" +
      "ient_streaming\030\005 \001(\010H\004\210\001\001\022\035\n\020server_stre" +
      "aming\030\006 \001(\010H\005\210\001\001\022\030\n\013description\030\007 \001(\tH\006\210" +
      "\001\001\022\020\n\010httpPath\030\010 \003(\t\022\022\n\nhttpMethod\030\t \003(\t" +
      "B\007\n\005_nameB\r\n\013_input_typeB\016\n\014_output_type" +
      "B\n\n\010_optionsB\023\n\021_client_streamingB\023\n\021_se" +
      "rver_streamingB\016\n\014_description\"{\n\016Servic" +
      "eOptions\022\027\n\ndeprecated\030! \001(\010H\000\210\001\001\022A\n\024uni" +
      "nterpreted_option\030\347\007 \003(\0132\".opensergo.api" +
      ".UninterpretedOptionB\r\n\013_deprecated\"\261\002\n\r" +
      "MethodOptions\022\027\n\ndeprecated\030! \001(\010H\000\210\001\001\022M" +
      "\n\021idempotency_level\030\" \001(\0162-.opensergo.ap" +
      "i.MethodOptions.IdempotencyLevelH\001\210\001\001\022A\n" +
      "\024uninterpreted_option\030\347\007 \003(\0132\".opensergo" +
      ".api.UninterpretedOption\"P\n\020IdempotencyL" +
      "evel\022\027\n\023IDEMPOTENCY_UNKNOWN\020\000\022\023\n\017NO_SIDE" +
      "_EFFECTS\020\001\022\016\n\nIDEMPOTENT\020\002B\r\n\013_deprecate" +
      "dB\024\n\022_idempotency_level\"\263\003\n\023Uninterprete" +
      "dOption\0229\n\004name\030\002 \003(\0132+.opensergo.api.Un" +
      "interpretedOption.NamePart\022\035\n\020identifier" +
      "_value\030\003 \001(\tH\000\210\001\001\022\037\n\022positive_int_value\030" +
      "\004 \001(\004H\001\210\001\001\022\037\n\022negative_int_value\030\005 \001(\003H\002" +
      "\210\001\001\022\031\n\014double_value\030\006 \001(\001H\003\210\001\001\022\031\n\014string" +
      "_value\030\007 \001(\014H\004\210\001\001\022\034\n\017aggregate_value\030\010 \001" +
      "(\tH\005\210\001\001\0323\n\010NamePart\022\021\n\tname_part\030\001 \001(\t\022\024" +
      "\n\014is_extension\030\002 \001(\010B\023\n\021_identifier_valu" +
      "eB\025\n\023_positive_int_valueB\025\n\023_negative_in" +
      "t_valueB\017\n\r_double_valueB\017\n\r_string_valu" +
      "eB\022\n\020_aggregate_value\"2\n\024OneofDescriptor" +
      "Proto\022\021\n\004name\030\001 \001(\tH\000\210\001\001B\007\n\005_name\"\271\003\n\017De" +
      "scriptorProto\022\021\n\004name\030\001 \001(\tH\000\210\001\001\0222\n\005fiel" +
      "d\030\002 \003(\0132#.opensergo.api.FieldDescriptorP" +
      "roto\0226\n\textension\030\006 \003(\0132#.opensergo.api." +
      "FieldDescriptorProto\0227\n\noneof_decl\030\010 \003(\013" +
      "2#.opensergo.api.OneofDescriptorProto\0223\n" +
      "\007options\030\007 \001(\0132\035.opensergo.api.MessageOp" +
      "tionsH\001\210\001\001\022D\n\016reserved_range\030\t \003(\0132,.ope" +
      "nsergo.api.DescriptorProto.ReservedRange" +
      "\022\025\n\rreserved_name\030\n \003(\t\032G\n\rReservedRange" +
      "\022\022\n\005start\030\001 \001(\005H\000\210\001\001\022\020\n\003end\030\002 \001(\005H\001\210\001\001B\010" +
      "\n\006_startB\006\n\004_endB\007\n\005_nameB\n\n\010_options\"\252\001" +
      "\n\023EnumDescriptorProto\022\021\n\004name\030\001 \001(\tH\000\210\001\001" +
      "\0226\n\005value\030\002 \003(\0132\'.opensergo.api.EnumValu" +
      "eDescriptorProto\0223\n\007options\030\003 \001(\0132\035.open" +
      "sergo.api.MessageOptionsH\001\210\001\001B\007\n\005_nameB\n" +
      "\n\010_options\"\231\001\n\030EnumValueDescriptorProto\022" +
      "\021\n\004name\030\001 \001(\tH\000\210\001\001\022\023\n\006number\030\002 \001(\005H\001\210\001\001\022" +
      "5\n\007options\030\003 \001(\0132\037.opensergo.api.EnumVal" +
      "ueOptionsH\002\210\001\001B\007\n\005_nameB\t\n\007_numberB\n\n\010_o" +
      "ptions\":\n\020EnumValueOptions\022\027\n\ndeprecated" +
      "\030\001 \001(\010H\000\210\001\001B\r\n\013_deprecated\"8\n\016MessageOpt" +
      "ions\022\027\n\ndeprecated\030\003 \001(\010H\000\210\001\001B\r\n\013_deprec" +
      "ated\"\301\007\n\024FieldDescriptorProto\022\021\n\004name\030\001 " +
      "\001(\tH\000\210\001\001\022\023\n\006number\030\003 \001(\005H\001\210\001\001\022=\n\005label\030\004" +
      " \001(\0162).opensergo.api.FieldDescriptorProt" +
      "o.LabelH\002\210\001\001\022;\n\004type\030\005 \001(\0162(.opensergo.a" +
      "pi.FieldDescriptorProto.TypeH\003\210\001\001\022\026\n\ttyp" +
      "e_name\030\006 \001(\tH\004\210\001\001\022\025\n\010extendee\030\002 \001(\tH\005\210\001\001" +
      "\022\032\n\rdefault_value\030\007 \001(\tH\006\210\001\001\022\030\n\013oneof_in" +
      "dex\030\t \001(\005H\007\210\001\001\022\026\n\tjson_name\030\n \001(\tH\010\210\001\001\0221" +
      "\n\007options\030\010 \001(\0132\033.opensergo.api.FieldOpt" +
      "ionsH\t\210\001\001\022\034\n\017proto3_optional\030\021 \001(\010H\n\210\001\001\"" +
      "\312\002\n\004Type\022\022\n\016TYPE_UNIVERSAL\020\000\022\017\n\013TYPE_DOU" +
      "BLE\020\001\022\016\n\nTYPE_FLOAT\020\002\022\016\n\nTYPE_INT64\020\003\022\017\n" +
      "\013TYPE_UINT64\020\004\022\016\n\nTYPE_INT32\020\005\022\020\n\014TYPE_F" +
      "IXED64\020\006\022\020\n\014TYPE_FIXED32\020\007\022\r\n\tTYPE_BOOL\020" +
      "\010\022\017\n\013TYPE_STRING\020\t\022\016\n\nTYPE_GROUP\020\n\022\020\n\014TY" +
      "PE_MESSAGE\020\013\022\016\n\nTYPE_BYTES\020\014\022\017\n\013TYPE_UIN" +
      "T32\020\r\022\r\n\tTYPE_ENUM\020\016\022\021\n\rTYPE_SFIXED32\020\017\022" +
      "\021\n\rTYPE_SFIXED64\020\020\022\017\n\013TYPE_SINT32\020\021\022\017\n\013T" +
      "YPE_SINT64\020\022\"X\n\005Label\022\023\n\017LABEL_UNIVERSAL" +
      "\020\000\022\022\n\016LABEL_OPTIONAL\020\001\022\022\n\016LABEL_REQUIRED" +
      "\020\002\022\022\n\016LABEL_REPEATED\020\003B\007\n\005_nameB\t\n\007_numb" +
      "erB\010\n\006_labelB\007\n\005_typeB\014\n\n_type_nameB\013\n\t_" +
      "extendeeB\020\n\016_default_valueB\016\n\014_oneof_ind" +
      "exB\014\n\n_json_nameB\n\n\010_optionsB\022\n\020_proto3_" +
      "optional\"\366\003\n\014FieldOptions\0225\n\005ctype\030\001 \001(\016" +
      "2!.opensergo.api.FieldOptions.CTypeH\000\210\001\001" +
      "\022\023\n\006packed\030\002 \001(\010H\001\210\001\001\0227\n\006jstype\030\006 \001(\0162\"." +
      "opensergo.api.FieldOptions.JSTypeH\002\210\001\001\022\021" +
      "\n\004lazy\030\005 \001(\010H\003\210\001\001\022\034\n\017unverified_lazy\030\017 \001" +
      "(\010H\004\210\001\001\022\027\n\ndeprecated\030\003 \001(\010H\005\210\001\001\022\021\n\004weak" +
      "\030\n \001(\010H\006\210\001\001\022A\n\024uninterpreted_option\030\347\007 \003" +
      "(\0132\".opensergo.api.UninterpretedOption\"/" +
      "\n\005CType\022\n\n\006STRING\020\000\022\010\n\004CORD\020\001\022\020\n\014STRING_" +
      "PIECE\020\002\"5\n\006JSType\022\r\n\tJS_NORMAL\020\000\022\r\n\tJS_S" +
      "TRING\020\001\022\r\n\tJS_NUMBER\020\002B\010\n\006_ctypeB\t\n\007_pac" +
      "kedB\t\n\007_jstypeB\007\n\005_lazyB\022\n\020_unverified_l" +
      "azyB\r\n\013_deprecatedB\007\n\005_weakJ\004\010\004\020\0052m\n\017Met" +
      "adataService\022Z\n\016ReportMetadata\022$.openser" +
      "go.api.ReportMetadataRequest\032\".opensergo" +
      ".api.ReportMetadataReplyBl\n\037com.alibaba." +
      "opensergo.api.protoP\001Z8github.com/opense" +
      "rgo/opensergo-go/pkg/api/proto;metadata\242" +
      "\002\014OpenSergoAPIb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_opensergo_api_ReportMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opensergo_api_ReportMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_ReportMetadataRequest_descriptor,
        new java.lang.String[] { "ServiceContract", "Name", });
    internal_static_opensergo_api_ReportMetadataReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opensergo_api_ReportMetadataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_ReportMetadataReply_descriptor,
        new java.lang.String[] { });
    internal_static_opensergo_api_ServiceContractProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opensergo_api_ServiceContractProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_ServiceContractProto_descriptor,
        new java.lang.String[] { "Types", "Services", });
    internal_static_opensergo_api_ServiceDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opensergo_api_ServiceDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_ServiceDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Method", "Options", "Description", "Name", "Options", "Description", });
    internal_static_opensergo_api_MethodDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opensergo_api_MethodDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_MethodDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "InputType", "OutputType", "Options", "ClientStreaming", "ServerStreaming", "Description", "HttpPath", "HttpMethod", "Name", "InputType", "OutputType", "Options", "ClientStreaming", "ServerStreaming", "Description", });
    internal_static_opensergo_api_ServiceOptions_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_opensergo_api_ServiceOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_ServiceOptions_descriptor,
        new java.lang.String[] { "Deprecated", "UninterpretedOption", "Deprecated", });
    internal_static_opensergo_api_MethodOptions_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_opensergo_api_MethodOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_MethodOptions_descriptor,
        new java.lang.String[] { "Deprecated", "IdempotencyLevel", "UninterpretedOption", "Deprecated", "IdempotencyLevel", });
    internal_static_opensergo_api_UninterpretedOption_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_opensergo_api_UninterpretedOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_UninterpretedOption_descriptor,
        new java.lang.String[] { "Name", "IdentifierValue", "PositiveIntValue", "NegativeIntValue", "DoubleValue", "StringValue", "AggregateValue", "IdentifierValue", "PositiveIntValue", "NegativeIntValue", "DoubleValue", "StringValue", "AggregateValue", });
    internal_static_opensergo_api_UninterpretedOption_NamePart_descriptor =
      internal_static_opensergo_api_UninterpretedOption_descriptor.getNestedTypes().get(0);
    internal_static_opensergo_api_UninterpretedOption_NamePart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_UninterpretedOption_NamePart_descriptor,
        new java.lang.String[] { "NamePart", "IsExtension", });
    internal_static_opensergo_api_OneofDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_opensergo_api_OneofDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_OneofDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Name", });
    internal_static_opensergo_api_DescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_opensergo_api_DescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_DescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Field", "Extension", "OneofDecl", "Options", "ReservedRange", "ReservedName", "Name", "Options", });
    internal_static_opensergo_api_DescriptorProto_ReservedRange_descriptor =
      internal_static_opensergo_api_DescriptorProto_descriptor.getNestedTypes().get(0);
    internal_static_opensergo_api_DescriptorProto_ReservedRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_DescriptorProto_ReservedRange_descriptor,
        new java.lang.String[] { "Start", "End", "Start", "End", });
    internal_static_opensergo_api_EnumDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_opensergo_api_EnumDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_EnumDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Value", "Options", "Name", "Options", });
    internal_static_opensergo_api_EnumValueDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_opensergo_api_EnumValueDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_EnumValueDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Number", "Options", "Name", "Number", "Options", });
    internal_static_opensergo_api_EnumValueOptions_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_opensergo_api_EnumValueOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_EnumValueOptions_descriptor,
        new java.lang.String[] { "Deprecated", "Deprecated", });
    internal_static_opensergo_api_MessageOptions_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_opensergo_api_MessageOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_MessageOptions_descriptor,
        new java.lang.String[] { "Deprecated", "Deprecated", });
    internal_static_opensergo_api_FieldDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_opensergo_api_FieldDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_FieldDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Number", "Label", "Type", "TypeName", "Extendee", "DefaultValue", "OneofIndex", "JsonName", "Options", "Proto3Optional", "Name", "Number", "Label", "Type", "TypeName", "Extendee", "DefaultValue", "OneofIndex", "JsonName", "Options", "Proto3Optional", });
    internal_static_opensergo_api_FieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_opensergo_api_FieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opensergo_api_FieldOptions_descriptor,
        new java.lang.String[] { "Ctype", "Packed", "Jstype", "Lazy", "UnverifiedLazy", "Deprecated", "Weak", "UninterpretedOption", "Ctype", "Packed", "Jstype", "Lazy", "UnverifiedLazy", "Deprecated", "Weak", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
