// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: specification/proto/servicecontract.proto

package com.alibaba.opensergo.api.proto;

public interface ServiceOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opensergo.api.ServiceOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Is this service deprecated?
   * Depending on the target platform, this can emit Deprecated annotations
   * for the service, or it will be completely ignored; in the very least,
   * this is a formalization for deprecating services.
   * </pre>
   *
   * <code>optional bool deprecated = 33;</code>
   * @return Whether the deprecated field is set.
   */
  boolean hasDeprecated();
  /**
   * <pre>
   * Is this service deprecated?
   * Depending on the target platform, this can emit Deprecated annotations
   * for the service, or it will be completely ignored; in the very least,
   * this is a formalization for deprecating services.
   * </pre>
   *
   * <code>optional bool deprecated = 33;</code>
   * @return The deprecated.
   */
  boolean getDeprecated();

  /**
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   *
   * <code>repeated .opensergo.api.UninterpretedOption uninterpreted_option = 999;</code>
   */
  java.util.List<com.alibaba.opensergo.api.proto.UninterpretedOption> 
      getUninterpretedOptionList();
  /**
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   *
   * <code>repeated .opensergo.api.UninterpretedOption uninterpreted_option = 999;</code>
   */
  com.alibaba.opensergo.api.proto.UninterpretedOption getUninterpretedOption(int index);
  /**
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   *
   * <code>repeated .opensergo.api.UninterpretedOption uninterpreted_option = 999;</code>
   */
  int getUninterpretedOptionCount();
  /**
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   *
   * <code>repeated .opensergo.api.UninterpretedOption uninterpreted_option = 999;</code>
   */
  java.util.List<? extends com.alibaba.opensergo.api.proto.UninterpretedOptionOrBuilder> 
      getUninterpretedOptionOrBuilderList();
  /**
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   *
   * <code>repeated .opensergo.api.UninterpretedOption uninterpreted_option = 999;</code>
   */
  com.alibaba.opensergo.api.proto.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(
      int index);
}
